# Indicator Configuration File
# This file contains all configuration parameters for technical indicators

bollinger_bands:
  timeframes:
    "1d":
      period: 20                      # Standard daily period
      std_dev_multiplier: 2.0         # Standard multiplier for daily
      squeeze_threshold: 0.05
      breakout_period: 5
      percent_b_overbought: 0.8
      percent_b_oversold: 0.2
    "1w":
      period: 20                      # Weekly analysis (20 weeks = ~5 months)
      std_dev_multiplier: 2.1         # Slightly higher for weekly volatility
      squeeze_threshold: 0.04         # Tighter squeeze for weekly
      breakout_period: 3              # Shorter confirmation for weekly
      percent_b_overbought: 0.85
      percent_b_oversold: 0.15
    "1M":
      period: 15                      # Monthly analysis (15 months coverage)
      std_dev_multiplier: 2.2         # Higher multiplier for monthly volatility
      squeeze_threshold: 0.03         # Even tighter for monthly
      breakout_period: 2              # Shorter confirmation for monthly
      percent_b_overbought: 0.9
      percent_b_oversold: 0.1
  params:
    price_source: "close"             # Standard source for calculation
    ma_type: "sma"                    # Simple Moving Average (Bollinger original specification)
    volume_confirmation: false        # Optional volume confirmation for signals
    bandwidth_ma_period: 10           # Period for bandwidth moving average
    squeeze_percentile_low: 20        # Low percentile for squeeze detection
    squeeze_percentile_high: 80       # High percentile for squeeze detection
    overbought_offset: 0.0            # Offset for overbought threshold
    oversold_offset: 0.0              # Offset for oversold threshold
    sma_slope_period: 2               # Period for SMA slope calculation
    position_threshold_pct: 1.0       # Position threshold percentage
    confidence_weights:               # Weights for confidence scoring
      squeeze: 0.2
      sma_slope: 0.3
      position_from_sma: 0.5

chaikin_money_flow:
  timeframes:
    "1d":
      period: 21
      divergence_period: 5
      volume_ma_period: 20
      bullish_threshold: 0.05
      bearish_threshold: -0.05
    "1w":
      period: 12
      divergence_period: 3
      volume_ma_period: 12
      bullish_threshold: 0.08
      bearish_threshold: -0.08
    "1M":
      period: 6
      divergence_period: 2
      volume_ma_period: 6
      bullish_threshold: 0.12
      bearish_threshold: -0.12
  params:
    zero_line: 0.0
    strong_bullish: 0.25
    strong_bearish: -0.25
    price_trend_strength: 0.02
    cmf_trend_strength: 0.05
    high_volume_multiplier: 1.5

donchian_channel:
  timeframes:
    "1d":
      period: 20
      breakout_confirmation: 1
      channel_width_threshold: 0.05
      trend_strength_period: 10
      reversal_zone_pct: 0.1
    "1w":
      period: 10
      breakout_confirmation: 1
      channel_width_threshold: 0.04
      trend_strength_period: 6
      reversal_zone_pct: 0.15
    "1M":
      period: 6
      breakout_confirmation: 1
      channel_width_threshold: 0.03
      trend_strength_period: 4
      reversal_zone_pct: 0.2
  params:
    middle_line: true
    price_source: "high_low"
    volume_confirmation: false
    volatility_percentile: 80
    support_resistance_levels: 3
    position_threshold_pct: 1.0
    signal_sensitivity: "normal"
    false_breakout_filter: true
    min_breakout_distance: 0.001

ema_20_50:
  timeframes:
    "1d":
      ema_fast_period: 20
      ema_slow_period: 50
      crossover_confirmation_periods: 2
      trend_strength_threshold: 0.001
      volume_ma_period: 20
    "1w":
      ema_fast_period: 10
      ema_slow_period: 25
      crossover_confirmation_periods: 1
      trend_strength_threshold: 0.002
      volume_ma_period: 10
    "1M":
      ema_fast_period: 6
      ema_slow_period: 12
      crossover_confirmation_periods: 1
      trend_strength_threshold: 0.005
      volume_ma_period: 6
  params:
    price_source: "close"
    volume_confirmation: false
    divergence_lookback: 10
    position_threshold_pct: 0.5
    stop_loss_atr_multiplier: 2.0
    take_profit_ratio: 2.0
    max_lookback_periods: 100
    confidence_weights:
      crossover_strength: 0.4
      trend_consistency: 0.3
      volume_confirmation: 0.2
      divergence_absence: 0.1

ichimoku_cloud:
  timeframes:
    "1d":
      tenkan_period: 9
      kijun_period: 26
      senkou_span_b_period: 52
      displacement: 26
      cloud_thickness_threshold: 0.01
      breakout_confirmation_periods: 3
    "1w":
      tenkan_period: 5
      kijun_period: 13
      senkou_span_b_period: 26
      displacement: 13
      cloud_thickness_threshold: 0.015
      breakout_confirmation_periods: 2
    "1M":
      tenkan_period: 3
      kijun_period: 6
      senkou_span_b_period: 12
      displacement: 6
      cloud_thickness_threshold: 0.02
      breakout_confirmation_periods: 1
  params:
    trend_confirmation: true
    price_cloud_buffer: 0.002
    momentum_confirmation: true
    support_resistance_levels: 5
    trend_strength_threshold: 0.5

keltner_channel:
  timeframes:
    "1d":
      ema_period: 20
      atr_period: 10
      atr_multiplier: 2.0
      squeeze_threshold: 0.05
      breakout_period: 5
      channel_position_upper: 0.8
      channel_position_lower: 0.2
    "1w":
      ema_period: 10
      atr_period: 7
      atr_multiplier: 1.8
      squeeze_threshold: 0.04
      breakout_period: 3
      channel_position_upper: 0.85
      channel_position_lower: 0.15
    "1M":
      ema_period: 6
      atr_period: 5
      atr_multiplier: 1.5
      squeeze_threshold: 0.03
      breakout_period: 2
      channel_position_upper: 0.9
      channel_position_lower: 0.1
  params:
    price_source: "typical"
    ma_type: "ema"
    volume_confirmation: false
    trend_strength_period: 10
    volatility_expansion_threshold: 1.5
    momentum_period: 14

macd:
  timeframes:
    "1d":
      fast_period: 12
      slow_period: 26
      signal_period: 9
      zero_line_threshold: 0.0001
      signal_threshold: 0.0001
      divergence_lookback: 14
    "1w":
      fast_period: 6
      slow_period: 13
      signal_period: 5
      zero_line_threshold: 0.0002
      signal_threshold: 0.0002
      divergence_lookback: 8
    "1M":
      fast_period: 3
      slow_period: 6
      signal_period: 3
      zero_line_threshold: 0.0005
      signal_threshold: 0.0005
      divergence_lookback: 4
  params:
    price_source: "close"
    histogram_threshold: 0.001
    trend_confirmation_periods: 3
    momentum_smoothing: false
    use_percentage: false
    centerline_oscillation: true
    histogram_divergence: true

obv:
  timeframes:
    "1d":
      smoothing_period: 0
      signal_line_period: 10
      divergence_period: 14
      trend_confirmation_period: 5
      trend_strength_period: 20
      momentum_period: 10
    "1w":
      smoothing_period: 3
      signal_line_period: 6
      divergence_period: 8
      trend_confirmation_period: 3
      trend_strength_period: 12
      momentum_period: 6
    "1M":
      smoothing_period: 5
      signal_line_period: 4
      divergence_period: 4
      trend_confirmation_period: 2
      trend_strength_period: 6
      momentum_period: 3
  params:
    smoothing_type: "sma"
    volume_threshold: 1.0
    price_change_threshold: 0.001
    breakout_threshold: 0.02
    divergence_min_periods: 5

parabolic_sar:
  timeframes:
    "1d":
      af_initial: 0.02
      af_increment: 0.02
      af_maximum: 0.20
      trend_confirmation_periods: 3
      price_deviation_threshold: 0.02
    "1w":
      af_initial: 0.015
      af_increment: 0.015
      af_maximum: 0.15
      trend_confirmation_periods: 2
      price_deviation_threshold: 0.03
    "1M":
      af_initial: 0.01
      af_increment: 0.01
      af_maximum: 0.10
      trend_confirmation_periods: 1
      price_deviation_threshold: 0.05
  params:
    signal_strength_threshold: 0.5
    volume_confirmation: false
    volume_ma_period: 20
    sar_distance_factor: 1.0
    trend_strength_periods: 10
    reversal_confirmation: true
    extreme_point_buffer: 0.001

pivot_point:
  params:
    calculation_method: "standard"
    period_type: "previous"
    include_opening: false
    emphasize_close: false
    support_levels: 3
    resistance_levels: 3
    central_pivot_range: false
    trend_confirmation: true
    breakout_threshold: 0.001
    volume_confirmation: false
    price_source: "hlc"
    strong_support_multiplier: 1.5
    weak_support_multiplier: 0.5
    pivot_zone_width: 0.002
    momentum_period: 5
    volume_ma_period: 20
    max_distance_from_pivot: 0.05
    confluence_bonus: 0.2
    time_decay_factor: 0.1

renko:
  timeframes:
    "1d":
      atr_period: 14
      atr_multiplier: 1.0
      percent_size: 0.5
      min_trend_bricks: 3
      breakout_lookback: 5
    "1w":
      atr_period: 10
      atr_multiplier: 0.8
      percent_size: 0.8
      min_trend_bricks: 2
      breakout_lookback: 3
    "1M":
      atr_period: 6
      atr_multiplier: 0.6
      percent_size: 1.2
      min_trend_bricks: 2
      breakout_lookback: 2
  params:
    brick_size: null
    auto_brick_method: "atr"
    price_source: "close"
    wick_calculation: true
    trend_reversal_bricks: 2
    volume_confirmation: false
    rsi_filter: false
    rsi_period: 14
    rsi_overbought: 70
    rsi_oversold: 30

rsi:
  timeframes:
    "1d":
      period: 14
      overbought_level: 70.0
      oversold_level: 30.0
      extreme_overbought: 80.0
      extreme_oversold: 20.0
      momentum_threshold: 2.0
      divergence_lookback: 5
    "1w":
      period: 10
      overbought_level: 75.0
      oversold_level: 25.0
      extreme_overbought: 85.0
      extreme_oversold: 15.0
      momentum_threshold: 3.0
      divergence_lookback: 3
    "1M":
      period: 6
      overbought_level: 80.0
      oversold_level: 20.0
      extreme_overbought: 90.0
      extreme_oversold: 10.0
      momentum_threshold: 5.0
      divergence_lookback: 2
  params:
    price_source: "close"
    smoothing_method: "wilder"
    midline: 50.0
    trend_filter_period: 20
    use_trend_filter: false
    signal_confirmation: true
    failure_swing_enabled: true
    hidden_divergence: false

supertrend:
  timeframes:
    "1d":
      atr_period: 10
      multiplier: 3.0
      trend_confirmation_period: 3
      signal_strength_period: 5
      volume_ma_period: 20
    "1w":
      atr_period: 7
      multiplier: 2.5
      trend_confirmation_period: 2
      signal_strength_period: 3
      volume_ma_period: 10
    "1M":
      atr_period: 5
      multiplier: 2.0
      trend_confirmation_period: 1
      signal_strength_period: 2
      volume_ma_period: 6
  params:
    use_hl2: true
    volume_confirmation: false
    breakout_confirmation: true
    support_resistance_levels: 3
    trend_momentum_period: 14
    price_action_filter: true
    volatility_filter: false
    atr_volatility_threshold: 1.5

vwap:
  params:
    price_source: "hlc3"
    session_reset: "daily"
    volume_threshold: 0
    periods_lookback: null
    use_ohlc4: false
    use_close: false
    use_hl2: false
    deviation_bands: true
    std_dev_multiplier: [1.0, 2.0]
    volume_profile: false
    session_high_low: true
    trend_confirmation_periods: 5
    volume_spike_threshold: 1.5
    price_deviation_threshold: 0.02